#+TITLE: SELECT part 2
#+SETUPFILE: ../../theme-bigblow-local.setup
#+OPTIONS: num:nil
#+OPTIONS: ^:nil
#+PROPERTY: header-args:sqlite :db week_4.sqlite :dir db/ :colnames yes :exports code
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="assets/session.css"/>
#+HTML_HEAD: <script type="text/javascript" src="assets/session.js"></script>

[[./../../index.org][Lunch And Learn SQL in 2020]]

* SELECT part 2

  Together stronger we are.

** Start

   After starting sqlite in the main directory as described in [[../../index.html#workshop-instructions][Instructions]], type:
   #+begin_src sqlite :tangle sql/04-start.sql
   .open sessions/03/db/week_4.sqlite
   #+end_src

** Theory

INNER JOIN
LEFT OUTER JOIN
RIGHT OUTER JOIN
FULL JOIN
CROSS JOIN
UNION

 #+begin_example
 #+end_example

** INNER JOIN

   Syntax

   #+begin_example
   #+end_example

   Example

   #+begin_src sqlite :tangle sql/04-inner-join.sql
   #+end_src

   Practice

   #+begin_export html
   <div class="answer">
   <button>Toggle Answer</button> Please, try it yourself first before revealing the answer.
   #+end_export

   #+begin_src sqlite :tangle sql/04-inner-join.sql
   #+end_src

   #+begin_export html
   </div>
   #+end_export

** LEFT OUTER JOIN

   Syntax

   #+begin_example
   #+end_example

   Example

   #+begin_src sqlite :tangle sql/04-left-outer-join.sql
   #+end_src

   Practice

   #+begin_export html
   <div class="answer">
   <button>Toggle Answer</button> Please, try it yourself first before revealing the answer.
   #+end_export

   #+begin_src sqlite :tangle sql/04-left-outer-join-answer.sql
   #+end_src

   #+begin_export html
   </div>
   #+end_export

** RIGHT OUTER JOIN

   Syntax

   #+begin_example
   #+end_example

   Example

   #+begin_src sqlite :tangle sql/04-right-outer-join.sql
   #+end_src

   Practice

   #+begin_export html
   <div class="answer">
   <button>Toggle Answer</button> Please, try it yourself first before revealing the answer.
   #+end_export

   #+begin_src sqlite :tangle sql/04-right-outer-join-answer.sql
   #+end_src

   #+begin_export html
   </div>
   #+end_export

** FULL JOIN

   Syntax

   #+begin_example
   #+end_example

   Example

   #+begin_src sqlite :tangle sql/04-full-join.sql
   #+end_src

   Practice

   #+begin_export html
   <div class="answer">
   <button>Toggle Answer</button> Please, try it yourself first before revealing the answer.
   #+end_export

   #+begin_src sqlite :tangle sql/04-full-join-answer.sql
   #+end_src

   #+begin_export html
   </div>
   #+end_export


** CROSS JOIN

   Syntax

   #+begin_example
   #+end_example

   Example

   #+begin_src sqlite :tangle sql/04-cross-join.sql
   #+end_src

   Practice

   #+begin_export html
   <div class="answer">
   <button>Toggle Answer</button> Please, try it yourself first before revealing the answer.
   #+end_export

   #+begin_src sqlite :tangle sql/04-cross-join-answer.sql
   #+end_src

   #+begin_export html
   </div>
   #+end_export

** UNION

   Syntax

   #+begin_example
   #+end_example

   Example

   #+begin_src sqlite :tangle sql/04-union.sql

   #+end_src

   Practice

   #+begin_export html
   <div class="answer">
   <button>Toggle Answer</button> Please, try it yourself first before revealing the answer.
   #+end_export

   #+begin_src sqlite :tangle sql/04-inner-union-answer.sql
   #+end_src

   #+begin_export html
   </div>
   #+end_export

** Further reading
