#+TITLE: PostgreSQL
#+SETUPFILE: ../../theme-bigblow-local.setup
#+OPTIONS: num:nil
#+OPTIONS: ^:nil
#+PROPERTY: header-args:sqlite :db week_5.sqlite :dir db/ :colnames yes :exports code
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="assets/session.css"/>
#+HTML_HEAD: <script type="text/javascript" src="assets/session.js"></script>

[[./../../index.org][Lunch And Learn SQL in 2020]]

* PostgreSQL

** DATABASE

** SCHEMA

There are several reasons why one might want to use schemas:

-  To allow many users to use one database without interfering with each other.

- To organize database objects into logical groups to make them more manageable.

- Third-party applications can be put into separate schemas so they do not collide with the names of other
 objects.

Schemas are analogous to directories at the operating system level, except that schemas cannot be nested.

#+begin_example

CREATE SCHEMA myschema;

#+end_example


DROP SCHEMA myschema;

To drop a schema including all contained objects, use:

DROP SCHEMA myschema CASCADE;

created tables without specifying any schema names. By default such tables (and
other objects) are automatically put into a schema named “public”.

search path

SHOW search_path;


** TABLE

*** CREATE TABLE
     #+begin_src sqlite
       CREATE TABLE bar (
        id INTEGER PRIMARY KEY,
        title TEXT);
     #+end_src

     #+RESULTS:

*** ALTER TABLE

**** Add new column

     #+begin_example
     ALTER TABLE <table_name> ADD COLUMN <column definition>;
     #+end_example

     #+begin_src sqlite :results output silent
     ALTER TABLE foo ADD COLUMN colour TEXT;
     #+end_src

     #+RESULTS:

     #+begin_src sqlite
     .schema foo
     #+end_src

     #+RESULTS:
     | CREATE TABLE foo (a_column | colour TEXT); |
     |----------------------------+---------------|

**** Rename table

     #+begin_example
     ALTER TABLE <table_name> RENAME TO <new_table_name>;
     #+end_example

     #+begin_src sqlite :results output silent
     ALTER TABLE foo RENAME TO foo2;
     #+end_src

     #+begin_src sqlite
     .tables
     #+end_src

     #+RESULTS:
     | foo2 |
     |------|

*** DROP TABLE

    Deleting table

    Syntax

    #+begin_example
    DROP TABLE <table_name>;
    #+end_example

    #+begin_example
    DROP TABLE IF EXISTS <table_name>;
    #+end_example

    Example

    #+begin_src sqlite
    DROP TABLE foo;
    #+end_src

    #+begin_src sqlite :results output silent
    DROP TABLE IF EXISTS foo;
    #+end_src


** INDEXES and CONSTRAINTS

   #+begin_src sqlite :results output silent
   CREATE UNIQUE INDEX br_title_idx ON bar (title);
   #+end_src

** INSERT
** UPDATE
** DELETE
** SELECT
